#------------- General Configurations -------------#
misc:
# Supported Values: train (Training), test (Testing), inference (Testing 2.0, patching supported)
  mode: "train"
#---------- Logging Level Configurations ----------#
  logging:
    filename: "VNET_Aug0_"
    level: "info"
#------------ GPU-Based Configurations ------------#
  gpu:
    alw_para_prs: True # Allow parallel processing across multiple GPUs.
    strategy: "mirrored" # Which strategy to apply when parallel processing is allowed.
    no_gpus: "9" # Which GPUs to be used for processing.
#------------- Training Configurations ------------#
train:
  model_type: "vnet"
# Number of iterations per epoch. If < 0, then (batch_size / total datapoints)
  num_iter: 200
  epochs: 200
# Comma/space separated list of metrics to be calculated.
# Currently supporting: acc (Accuracy), mean_iou (Mean Intersection over Union), dice-coef (Dice Coefficient),
# recall (Recall), and prec (Precision).
  perf_metrics: "recall, prec, mean_iou, dice_coef"
# Possible values: leakyrelu, relu, snake, gelu, prelu
  activation: "prelu"
  output_classes: 1
  dropout: 0.2
  min_filter: 4
# Possible values: adam, sgd, rmsprop, adadelta, adamax, adagrad
  optimizer: "adam"
  learning_rate: 0.001
 # Whether to use learning rate schedular or not. Configurations for it are in "config_lrs.yml"
  aply_lr_sch: False
  loss: "dice"
  #--------------- Data Configurations --------------#
  data:
  # Input Path can contain multiple sources comma-separated. The file naming convention should be the
  # same in both sources. Image and Label extensions should be same in all input sources.
    inputs: "/home/mmal151/Desktop/Dummy_Data/T1"
    img_ext: "T1_bet_BC.nii.gz"
    lbl_ext: "LESION.nii.gz"
    image_shape: "(197, 233, 189)"
    batch_size: 4
# Remove previous augmented results.
    rem_pre_aug: True
# Normalize Data (using Standardization)
    norm_data: True
    shuffle: True
#---------- Same Test Data Configurations ---------#
    test:
        alw_test: False # Use same source for test data
        ratio: 0.2
        seed: 2023
#--------- Validation Data Configurations ---------#
    valid:
        ratio: 0.2
        seed: 2024
#----------- Patch Related Configurations ---------#
    patch:
      alw_patching: True
      patch_size: "(128, 128, 128)"
      random_patches: False # If False, total_patches will be used as a stride.
      total_patches: 32
#-------- Data Augmentation Configurations --------#
    augmentation:
      alw_aug: True
      factor: 0.3
      technique: "cravemix"
#---------- Model Related Configurations ----------#
  resume:
    resume_train: False
    model_path: "vnet_13.h5"
#--------- Model State Save Configurations --------#
  save:
    model_name: "vnet_"
    best_only: True # If True, only best model will be saved
#------------- Testing Configurations -------------#
test:
  model:
    load_path: "vnet_182.h5"
  data:
    inputs: "/home/mmal151/Desktop/Dummy_Data/T1"
    img_ext: "T1_bet_BC.nii.gz"
    lbl_ext: "LESION.nii.gz"
    image_shape: "(140, 144, 140)"
#----------- Patch Related Configurations ---------#
# Should matching the training configurations
    patch:
      alw_patching: True
      patch_size: "(128, 128, 128)"
      stride: 32 # If -1, the number of patches will be (img.shape / patch_size) + 1.
#-------------- Save Random Samples ---------------#
  samples:
    save_samples: True
    no_samples: 5
    random_samples: True


