logging_config:
  filename: "UNET_"
  level: "info"
common_config:
  process: "test"
  parallel_process: False
  gpus: "2,3,4"
  model_type: 'unet'
data:
  input_path: "/home/mmal151/Desktop/Dummy_Data/INPUT"
  img_ext: "T1_brain_cropped.nii.gz"
  lbl_ext: "LESION_cropped.nii.gz"
  min_filter: 64
  image_shape: "(140,170,144)"
  output_classes: 1
  seed: 2023
  apply_augmentation: True
augmentation:
  factor: 0.3
  technique: cravemix
train:
  valid_ratio: 0.2
  batch_size: 4
  dropout: 0.2
  learning_rate: 0.0001
  model_name: unet_
  epochs: 50
test:
  model_load_state: "/home/mmal151/Desktop/GIthub-Repo/Model_State/Unet_3D/No-Augmentation/unet_50.h5"
  save_random_samples: True
  num_samples: 1


