learning_schedular:
  type: "cosine" #Which type of learning schedular to use. Possible Values: cosine, exponential
  decay_steps: -1 # Default value will be used. It may vary depending on the type of the schedular.

  cosine:
    warmup_steps: 1000 # If <=0, default value be used.

  exponential:
    decay_rate: 0.96 # If < -1 default value be used.

  polynomial:
    end_learning_rate: 0.01


