logging_config:
  filename: "UNET_Aug30_"
  level: "info" # Need to change this for production
#------------------------------------------------------#
common_config:
  process: "train"
  parallel_process: True
  gpus: "0,1,2"
  model_type: 'vnet'
#------------------------------------------------------#
data:
  #Input Path can contain multiple sources comma-separated. The file naming convention should be the same in both sources.
  input_path: "/home/mmal151/Desktop/Dummy_Data/T1"
  #input_path: "/hpc/mmal151/ATLAS_Cleaned"
  img_ext: "T1_bet_BC.nii.gz"
  lbl_ext: "LESION.nii.gz"
  min_filter: 4
  image_shape: "(128, 128, 128)"
  output_classes: 1
  seed: 2023
  apply_augmentation: False
  apply_norm: False  # Apply normalization (Standardization) on the input image.
  shuffle: True  # Shuffle data at the end of every epoch.
#------------------------------------------------------#
augmentation:
  #In case of multiple input sources augmentation will be applied separately on each data source.
  #Same augmentation settings will be used for each data source.
  factor: 0.3
  technique: cravemix
  rem_pre_aug: True # Remove previous augmentations
#------------------------------------------------------#
train:
  resume_training: False
  model_file: /home/mmal151/Desktop/GIthub-Repo/Model_State/VNet/No_Aug_Dice_Loss/vnet_50.h5
  valid_ratio: 0.1
  batch_size: 2
  dropout: 0.2
  learning_rate: 0.0001
  model_name: unet_
  epochs: 5
  save_best_only: True # Configuration for "save_best_only" in Model Checkpoints.
  test_on_same_data: False  # If True testing is performed within the training flow.
  test_ratio: 0.2 # Will only be checked if "test_on_same_data" is True.
  activation: "prelu" # Possible values: leakyrelu, relu, snake, gelu, prelu
  optimizer: "Adam" # Possible values: adam, sgd, rmsprop, adadelta, adamax, adagrad
  apply_lr_sch: True # Apply learning rate schedular. Learning Rate related configurations will be read from config_lrs.yml
  loss: "dice" # Possible custom losses: dice, tverskycoef, tversky, ftversky (focal tversky).
  # If loss function doesn't exist in the custom losses' list, it will be returned as is.
  perf_metrics: "recall, prec, mean_iou, dice_coef" # Comma/space separated list of metrics to be calculated.
  # Currently supporting: acc (Accuracy), mean_iou (Mean Intersection over Union), dice-coef (Dice Coefficient),
  # recall (Recall), and prec (Precision).
#------------------------------------------------------#
model_specific: # Will only be checked if the particular model is being used.
#------------------------------------------------------#
  vnet:
    num_encoder_blocks: "1,2,3,3" # Number of convolutional blocks in each encoder layer.
    num_decoder_blocks: "3,3,2" # Number of convolutional blocks in each decoder layer.
    use_transpose: True # Use Transpose Convolutions for upscaling.
    use_sne_layer: False # Use squeeze and excitation layer for each residual connection
#------------------------------------------------------#
test:
  model_load_state: "unet_01_temp.h5"
  save_random_samples: False
  num_samples: 1
#------------------------------------------------------#


