output_classes: 1
dropout: 0.2
min_filter: 8
# -- V-Net Specific Configurations --#
vnet:
  encoder_blocks: "1,2,3,3"
  decoder_blocks: "3,3,4"
  use_transpose: True
  add_both_res_con: False # If true, instead of both res connection functions being applied in succession. They will be
  # applied independently and added in the end.
# Use squeeze and excitation block based residual connections, will be used for up-scaling.
  squeeze_excitation:
    use_sne: False
    ratio: 2
    use_relu: True
    use_res_con: True
  # Use dilated residual connections
  dilated_res_con:
    use_dltd_res_con: True
    dilation_rates: "1,2,4,8" # Must be 4, to match the number of up-sampling blocks.

